services:
  - type: web
    name: blogging-platform
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerFilePath: Dockerfile
    startCommand: >
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE_PATH
        value: /data/database.sqlite
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://blogging-platform.onrender.com
